FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf

RUN apt-get update && \
    apt-get install -y nginx-module-sticky-module && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]