version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: lior
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_logs:/var/log/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5001:5001"
    volumes:
      - app1_logs:/app/logs

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5002:5001"
    volumes:
      - app2_logs:/app/logs

  app3:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5003:5001"
    volumes:
      - app3_logs:/app/logs


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  app1_logs:
  app2_logs:
  app3_logs:
  db_data:
  db_logs:
